version = "1.0"

[main]
name.en = "List configuration"
name.fr = "Configuration de la liste"

help.en = "This is a simplified management interface. For advanced options, please refer to the documentation."
help.fr = "Il s’agit d’une interface de gestion simplifiée. Pour des options avancées, veuillez vous référer à la documentation."

    [main.general]
    name.en = "General"
    name.fr = "Général"

        [main.general.listadress]
        ask.en = "List adress"
        ask.fr = "Adresse de la liste"
        readonly = true
        type = "text"

        [main.general.sub_policy]
        ask.en = "Subscription policy"
        ask.fr = "Politique d'abonnement"
        type = "select"
        choices.open = "Anyone can subscribe or unsubscribe by email"
        choices.closedlistsub = "Restrict new subscriptions"
        choices.closedlist = "Restricts both new subscriptions and unsubscriptions"

        [main.general.post_policy]
        ask.en = "Posting policy"
        ask.fr = "Politique d'envoi de messages"
        type = "select"
        choices.all = "Anyone can post"
        choices.subonlypost = "Only people subscribed to the list can post"
        choices.modonlypost = "Only moderators can post"

    [main.owners]
    name.en = "Owners"
    name.fr = "Propriétaires"

        [main.owners.owner]
        ask.en = "List owners (one email per line)"
        ask.fr = "Propriétaires de la liste (un email par ligne)"
        help.en = "Technical setting name: `owner`"
        help.fr = "Nom technique du paramètre : `owner`"
        optional = true
        type = "text"
        bind = "__DATA_DIR__/control/owner"

        [main.owners.notifysub]
        ask.en = "Notify owners about subcriptions/unsubscribtions to the list?"
        ask.fr = "Notifier les propriétaires des abonnements/désabonnements à la liste"
        help.en = "Technical setting name: `notifysub`"
        help.fr = "Nom technique du paramètre : `notifysub`"
        type = "boolean"

        [main.owners.submod]
        ask.en = "Subscriptions to the list must be validated by owners"
        ask.fr = "Faire valider les inscriptions à la liste par les propriétaires"
        help.en = "Technical setting name: `submod`"
        help.fr = "Nom technique du paramètre : `submod`"
        type = "boolean"

    [main.moderation]
    name.en = "Moderation"
    name.fr = "Modération"

        [main.moderation.moderated]
        ask.en = "Enable moderation"
        ask.fr = "Activer la modération"
        help.en = "Technical setting name: `moderated`"
        help.fr = "Nom technique du paramètre : `moderated`"
        type = "boolean"

        [main.moderation.moderators]
        ask.en = "List moderators (one email per line)"
        ask.fr = "Modérateur·ice·s de la liste (une adresse courriel par ligne)"
        help.en = "Technical setting name: `moderators`"
        help.fr = "Nom technique du paramètre : `moderators`"
        type = "text"
        bind = "__DATA_DIR__/control/moderators"
        visible = "moderated == true"

        [main.moderation.modnonsubposts]
        ask.en = "Send posts to moderation if they are from unauthorized people (instead of simply denying them)"
        ask.fr = "Faire valider les messages par les modérateur·ice·s si ils provinnent de personnes non autorisées à poster (plutôt qu de simplement refuser les messages)"
        help.en = "Technical setting name: `modnonsubposts`"
        help.fr = "Nom technique du paramètre : `modnonsubposts`"
        type = "boolean"
        visible = "moderated == true"

        [main.moderation.notifymod]
        ask.en = "Notify authors that their post is pending moderation"
        ask.fr = "Notifier les personnes lorsque leur message est en attente de modération"
        help.en = "Technical setting name: `notifymod`"
        help.fr = "Nom technique du paramètre : `notifymod`"
        type = "boolean"
        visible = "moderated == true"

    [main.mail]
    name.en = "Mail configuration"
    name.fr = "Configuration des emails"

        [main.mail.prefix]
        ask.en = "Prefix for the Subject line of emails"
        ask.fr = "Préfixe pour la ligne d'objet des emails"
        help.en = "Technical setting name: `prefix`"
        help.fr = "Nom technique du paramètre : `prefix`"
        type = "string"

        [main.mail.footer]
        ask.en = "Footer content"
        ask.fr = "Contenu du pied de page"
        help.en = "Technical setting name: `footer`"
        help.fr = "Nom technique du paramètre : `footer`"
        type = "text"
        bind = "__DATA_DIR__/control/footer"

    [main.subscribers]
    name.en = "Subscribers"
    name.fr = "Abonné·e·s"

        [main.subscribers.add_subscribers]
        help.en = "A welcome email will be sent to added addresses."
        help.fr = "Un courriel de bienvenue sera envoyé aux adresses ajoutées."
        ask.en = "Add addresses to the standard subscribers category (one per line)"
        ask.fr = "Ajouter des adresses à la catégorie subscribers (une par ligne)"
        type = "text"

        [main.subscribers.del_subscribers]
        help.en = "A goodbye email will be sent to the removed addresses."
        help.fr = "Un courriel d’au revoir sera envoyé aux adresses supprimées."
        ask.en = "Remove addresses from the list (one per line)"
        ask.fr = "Retirer des adresses de la liste (une par ligne)"
        type = "text"

        [main.subscribers.display_subscribers]
        ask.en = "Display subscribers list"
        ask.fr = "Afficher la liste des abonné·e·s"
        type = "boolean"

        [main.subscribers.subscribers_list]
        readonly = true
        ask.en = "Subscribers"
        ask.fr = "Abonné·e·s"
        type = "text"
        visible = "display_subscribers"
        bind = "null"
