#schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mlmmj"
name = "Mailing List Manager"
description.en = "Simple and efficient mailing list manager"
description.fr = "Gestionnaire de liste de diffusion simple et efficace"
version = "1.4.3~ynh2"
maintainers = ["Raph"]

[upstream]
license = "MIT"
website = "https://mlmmj.org/"
admindoc = "https://mlmmj.org/README.html"
code = "https://codeberg.org/mlmmj/mlmmj"

[integration]
yunohost = ">= 11.2.29"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.list_email]
    ask.en = "Enter the full email address of the mailing list (e.g., mylist@mydomain.com)"
    ask.fr = "Entrez l'adresse e-mail complète de la liste de diffusion (par exemple, maliste@mondomaine.com)"
    example = "mylist@mydomain.com"
    help.en = "The email address must be available and the domain must be managed by this Yunohost instance with incoming and outgoing mail enabled."
    help.fr = "L'adresse e-mail doit être disponible et le domaine doit être géré par cette instance Yunohost avec le courriel entrant et sortant activé."
    type = "string"
    pattern.regexp = '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    pattern.error = "Please provide a valid email address in the format username@domain.com."

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["ast", "cs", "de", "en", "fi", "fr", "gr", "it", "pt", "sk", "zh-cn"]
    default = "en"
    
    [install.owner]
    ask.en = "Select the owner of the mailing list"
    ask.fr = "Sélectionnez le propriétaire de la liste de diffusion"
    help.en = "Owners of the mailing list can be added or removed after the initial setup through the Yunohost administration interface."
    help.fr = "Il est possible d'ajouter ou de supprimer des propriétaires de la liste de diffusion après la configuration initiale via l'interface d'administration de Yunohost."
    type = "user"

[resources]
  [resources.sources.main]
  url = "https://codeberg.org/mlmmj/mlmmj/releases/download/RELEASE_1_4_3/mlmmj-1.4.3.tar.xz"
  sha256 = "dcaee66232fa1d10d9d2352ceb03b05879dfba978368988af585b0697506f4a1"
  format = "tar.xz"
  in_subdir = true
  autoupdate.strategy = "latest_forgejo_release"
  autoupdate.asset = "^mlmmj-.*tar.xz$"

  [resources.sources.web]
  url = "https://github.com/ashledombos/mlmmj-simple-web-interface/archive/refs/tags/test.tar.gz"
  sha256 = "bcc09a7a573f84f8f15d82306a1cc5430ae6b6c440221a92ba7d4a92174f09bd"
        
    [resources.system_user]
    
    [resources.install_dir]
    
    [resources.permissions]

    [resources.ports]

    [resources.apt]
    packages = "autoconf make gcc pkg-config libatf-dev"
